language: generic
services:
  - docker
before_install:
  - docker build -t swathireddyg54/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true swathireddyg54/react-test npm run test -- --coverage
after_success:
  - docker build -t swathireddyg54/multi_client ./client
  - docker build -t swathireddyg54/multi_nginx ./nginx
  - docker build -t swathireddyg54/multi_server ./server
  - docker build -t swathireddyg54/multi_worker ./worker

# log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#take these images and push them to docker hub
  - docker push swathireddyg54/multi_client
  - docker push swathireddyg54/multi_nginx
  - docker push swathireddyg54/multi_server
  - docker push swathireddyg54/multi_worker
  


